name: On Pull Request

on:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install
